[package]
name = "flexi-parse"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = { version = "0.3", optional = true }
proc-macro2 = { version = "1.0", optional = true }

[features]
default = ["ariadne", "proc-macro2"]
ariadne = ["dep:ariadne"]
proc-macro = ["proc-macro2", "proc-macro2/proc-macro"]
proc-macro2 = ["dep:proc-macro2"]
