name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        rustup toolchain add stable --component clippy
        rustup override set stable
    - name: Build
      run: cargo build --verbose --all-features --workspace
    - name: Run tests
      run: cargo test --verbose --all-features --workspace
    - name: Run Clippy
      run: cargo clippy --verbose --all-features --workspace
  miri:
    name: Test with Miri
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          rustup toolchain add nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Run Miri
        run: 'cargo miri test --workspace --all-features --verbose'
